version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "3000:3000"
